using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Tofu.Tests;

[TestFixture]
public class TofuGeneratorTests
{
    private static GeneratorDriverRunResult RunGenerator(string source, params string[] additionalSources)
    {
        var syntaxTrees = new[] { source }.Concat(additionalSources)
            .Select(s => CSharpSyntaxTree.ParseText(s))
            .ToArray();

        var references = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrWhiteSpace(a.Location))
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .Cast<MetadataReference>()
            .ToList();

        references.Add(MetadataReference.CreateFromFile(typeof(Abstractions.ITofuMapperRegistrar).Assembly.Location));

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            syntaxTrees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new TofuGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);

        driver = (CSharpGeneratorDriver)driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out _,
            out _);

        return driver.GetRunResult();
    }

    [Test]
    public void Generator_WithNoRegistrars_GeneratesNoOutput()
    {
        var source = @"
namespace TestNamespace
{
    public class MyClass
    {
    }
}";

        var result = RunGenerator(source);

        Assert.That(result.GeneratedTrees.Length, Is.EqualTo(0));
    }

    [Test]
    public void Generator_WithRegistrarButNoEnumMappings_GeneratesEmptyExtensionClass()
    {
        var source = @"
using Tofu.Abstractions;

namespace TestNamespace
{
    public class MyRegistrar : ITofuMapperRegistrar
    {
        public void Register(ITofuMapperRegistry registry)
        {
            // No mappings
        }
    }
}";

        var result = RunGenerator(source);

        Assert.That(result.GeneratedTrees.Length, Is.EqualTo(1));
        
        var generatedSource = result.GeneratedTrees[0].ToString();
        Assert.That(generatedSource, Does.Contain("public static partial class TofuEnumExtensions"));
        Assert.That(generatedSource, Does.Contain("// <auto-generated />"));
    }

    [Test]
    public void Generator_WithEnumMapping_GeneratesExtensionMethod()
    {
        var source = @"
using Tofu.Abstractions;

namespace TestNamespace
{
    public enum SourceEnum
    {
        Value1,
        Value2
    }

    public enum DestinationEnum
    {
        Value1,
        Value2
    }

    public class MyRegistrar : ITofuMapperRegistrar
    {
        public void Register(ITofuMapperRegistry registry)
        {
            registry.Enum<SourceEnum, DestinationEnum>();
        }
    }
}";

        var result = RunGenerator(source);

        Assert.That(result.GeneratedTrees.Length, Is.EqualTo(1));
        
        var generatedSource = result.GeneratedTrees[0].ToString();
        
        Assert.That(generatedSource, Does.Contain("public static TestNamespace.DestinationEnum ToDestinationEnum(this TestNamespace.SourceEnum value)"));
        Assert.That(generatedSource, Does.Contain("=> throw new System.ArgumentOutOfRangeException"));
    }

    [Test]
    public void Generator_WithMultipleEnumMappings_GeneratesMultipleExtensionMethods()
    {
        var source = @"
using Tofu.Abstractions;

namespace TestNamespace
{
    public enum SourceEnum1 { A, B }
    public enum DestEnum1 { A, B }
    
    public enum SourceEnum2 { X, Y }
    public enum DestEnum2 { X, Y }

    public class MyRegistrar : ITofuMapperRegistrar
    {
        public void Register(ITofuMapperRegistry registry)
        {
            registry.Enum<SourceEnum1, DestEnum1>();
            registry.Enum<SourceEnum2, DestEnum2>();
        }
    }
}";

        var result = RunGenerator(source);

        Assert.That(result.GeneratedTrees.Length, Is.EqualTo(1));
        
        var generatedSource = result.GeneratedTrees[0].ToString();
        
        Assert.That(generatedSource, Does.Contain("ToDestEnum1"));
        Assert.That(generatedSource, Does.Contain("ToDestEnum2"));
    }

    [Test]
    public void Generator_WithMultipleRegistrars_GeneratesMultipleFiles()
    {
        var source = @"
using Tofu.Abstractions;

namespace TestNamespace
{
    public enum SourceEnum { A }
    public enum DestEnum { A }

    public class Registrar1 : ITofuMapperRegistrar
    {
        public void Register(ITofuMapperRegistry registry)
        {
            registry.Enum<SourceEnum, DestEnum>();
        }
    }

    public class Registrar2 : ITofuMapperRegistrar
    {
        public void Register(ITofuMapperRegistry registry)
        {
            registry.Enum<SourceEnum, DestEnum>();
        }
    }
}";

        var result = RunGenerator(source);

        Assert.That(result.GeneratedTrees.Length, Is.EqualTo(2));
        Assert.That(result.Results[0].GeneratedSources.Length, Is.EqualTo(2));
    }

    [Test]
    public void Generator_ProducesNoDiagnostics_ForValidInput()
    {
        var source = @"
using Tofu.Abstractions;

namespace TestNamespace
{
    public enum SourceEnum { A }
    public enum DestEnum { A }

    public class MyRegistrar : ITofuMapperRegistrar
    {
        public void Register(ITofuMapperRegistry registry)
        {
            registry.Enum<SourceEnum, DestEnum>();
        }
    }
}";

        var result = RunGenerator(source);

        Assert.That(result.Diagnostics.Length, Is.EqualTo(0));
    }

    [Test]
    public void Generator_WithClassNotImplementingInterface_GeneratesNothing()
    {
        var source = @"
namespace TestNamespace
{
    public class NotARegistrar
    {
        public void Register(object mapper)
        {
            // This is not implementing ITofuMapperRegistrar
        }
    }
}";

        var result = RunGenerator(source);

        Assert.That(result.GeneratedTrees.Length, Is.EqualTo(0));
    }

    [Test]
    public void Generator_WithNonEnumMethodCall_IgnoresIt()
    {
        var source = @"
using Tofu.Abstractions;

namespace TestNamespace
{
    public class MyRegistrar : ITofuMapperRegistrar
    {
        public void Register(ITofuMapperRegistry registry)
        {
            mapper.SomeOtherMethod();
        }
    }
}";

        var result = RunGenerator(source);

        // Should generate the class but with no methods
        Assert.That(result.GeneratedTrees.Length, Is.EqualTo(1));
        var generatedSource = result.GeneratedTrees[0].ToString();
        Assert.That(generatedSource, Does.Contain("public static partial class TofuEnumExtensions"));
    }

    [Test]
    public void Generator_GeneratedSourceHasCorrectFileName()
    {
        var source = @"
using Tofu.Abstractions;

namespace TestNamespace
{
    public enum SourceEnum { A }
    public enum DestEnum { A }

    public class MyRegistrar : ITofuMapperRegistrar
    {
        public void Register(ITofuMapperRegistry registry)
        {
            registry.Enum<SourceEnum, DestEnum>();
        }
    }
}";

        var result = RunGenerator(source);

        var generatedFile = result.Results[0].GeneratedSources[0];
        Assert.That(generatedFile.HintName, Is.EqualTo("MyRegistrarExtensions.g.cs"));
    }
}